### ISSUE TITLE
google android permission screen

### ISSUE THREAD

**Issue by pjebs** [apl-devs/Permissions-Helper#6]
Does google provide a standard Android permission screen which you replaced?

Your readme is a bit unclear.

**Comment by Andrew-Quebe** [comment]
No, this library was an attempt to recreate what Android Auto uses for requesting permissions at runtime.

From the readme: 
> I was exploring the Android Auto app when I noticed the way they present required permissions to the user. That got me thinking that I could create a library that does exactly that.

**Comment by pjebs** [comment]
how can you replace their native screen with yours?
