### ISSUE TITLE
Please update dependency

### ISSUE THREAD

**Issue by rammadogs** [apl-devs/Permissions-Helper#7]
When I try to import the Permissions-Helper library, it says that it failed to resolve com.android.support.constraint:constraint-layout:1.0.0-alpha1. It seems that in newer versions of android studio, alpha1 isn't available. Please update the dependency to use a newer version of the constraint layout.

**Comment by heinrichreimer** [comment]
@rammadogs Would you mind creating a quick PR?

**Comment by pjebs** [comment]
can you update the tag please
